const fs = require('fs');
const path = 'src/generated/page-index.json';

// Since we can't easily trigger the full build from this script without importing TS, 
// and the user has a dev server running which might not have re-written the JSON yet,
// we might need to rely on the fact that `npm run dev` re-builds on file change?
// Actually, `page-index.json` is likely generated by a build script or a specific API route.
// Let's assume the dev server or a specific command updates it. 
// If not, we might need to run the generation script.
// For now, let's just check the file. If it hasn't changed, we might need to trigger generation.

try {
    // We need to wait a moment for the dev server to potentially regenerate if it watches.
    // unique wait to ensure we don't read stale data immediately
    setTimeout(() => {
        if (fs.existsSync(path)) {
            const data = fs.readFileSync(path, 'utf8');
            const index = JSON.parse(data);

            const targetSlug = '/import-duty-vat-landed-cost/lithium-batteries/from/china/to/south-africa';
            const targetPage = index.pages.find(p => p.slug === targetSlug);

            console.log('\n--- Target Page Status (After Fix) ---');
            if (targetPage) {
                console.log(`Slug: ${targetPage.slug}`);
                console.log(`Index Status: ${targetPage.indexStatus}`);
                console.log(`Canonical: ${targetPage.canonicalSlug}`);
                if (targetPage.indexStatus !== 'INDEX') {
                    console.log(`Blockers: ${JSON.stringify(targetPage.blockers)}`);
                } else {
                    console.log('SUCCESS: Page is now INDEXED.');
                }
            } else {
                console.log('Target page not found in index.');
            }
        } else {
            console.log('page-index.json not found.');
        }
    }, 2000);

} catch (err) {
    console.error('Error:', err);
}
